# Created with WinGet Releaser using komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Firezone.Client.GUI
PackageVersion: 1.5.3
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{C85F976C-E60B-4A61-888D-D6E1AD8557CE}'
ReleaseDate: 2025-06-15
AppsAndFeaturesEntries:
- ProductCode: '{C85F976C-E60B-4A61-888D-D6E1AD8557CE}'
  UpgradeCode: '{8AEF9B86-7239-57FE-9F44-5E8928AAA545}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Firezone'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/firezone/firezone/releases/download/gui-client-1.5.3/firezone-client-gui-windows_1.5.3_x86_64.msi
  InstallerSha256: 5F79C0D3D50018C14A0CAEB23953671D53715862B8BE785A210E83BEF0314EB9
ManifestType: installer
ManifestVersion: 1.10.0
